# Generated by Django 4.1.1 on 2022-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0004_currency_language_alter_city_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="currency",
        ),
        migrations.AddField(
            model_name="country",
            name="currencies",
            field=models.ManyToManyField(blank=True, to="countries.currency"),
        ),
        migrations.AlterField(
            model_name="country",
            name="languages",
            field=models.ManyToManyField(blank=True, to="countries.language"),
        ),
    ]
